name: exchange_currency_rates_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  envied: ^0.5.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  dio: ^5.4.0
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  google_fonts: ^6.1.0
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.19+1
  sqlite3: ^2.0.0
  path_provider: ^2.1.2
  path: ^1.8.3
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  mocktail: ^1.0.3
  bloc_test: ^9.1.5
  json_serializable: ^6.7.1
  drift_dev: ^2.15.0

flutter:
  uses-material-design: true
